CREATE OR REPLACE VIEW REFERENCE.DIM_YEAR AS (
    SELECT
        DISTINCT
        YEAR(EventDate) AS YEAR,
        YEAR(EventDate)-1 AS YEAR_LY,
        YEAR(EventDate)-2 AS YEAR_LLY
    FROM REFERENCE.F1_CALENDER
    ORDER BY
        YEAR(EventDate) DESC
);
